# Generated by Django 5.2.5 on 2025-08-20 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenged',
            field=models.ForeignKey(help_text='Player who received the challenge', on_delete=django.db.models.deletion.CASCADE, related_name='received_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='challenger',
            field=models.ForeignKey(help_text='Player who sent the challenge', on_delete=django.db.models.deletion.CASCADE, related_name='sent_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='black_player',
            field=models.ForeignKey(help_text='Player with black stones', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(help_text='Player with white stones', on_delete=django.db.models.deletion.CASCADE, related_name='games_as_white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winner of the game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameevent',
            name='user',
            field=models.ForeignKey(help_text='User this event is for', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamemove',
            name='game',
            field=models.ForeignKey(help_text='Game this move belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game'),
        ),
        migrations.AddField(
            model_name='gamemove',
            name='player',
            field=models.ForeignKey(help_text='Player who made this move', on_delete=django.db.models.deletion.CASCADE, related_name='moves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playersession',
            name='current_game',
            field=models.ForeignKey(blank=True, help_text='Current game if player is in game', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='games.game'),
        ),
        migrations.AddField(
            model_name='playersession',
            name='user',
            field=models.ForeignKey(help_text='User this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='ruleset',
            field=models.ForeignKey(help_text='Rule set for this game', on_delete=django.db.models.deletion.RESTRICT, related_name='games', to='games.ruleset'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='ruleset',
            field=models.ForeignKey(blank=True, help_text='Rule set for the proposed game', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='games.ruleset'),
        ),
        migrations.AddIndex(
            model_name='gameevent',
            index=models.Index(fields=['user', 'consumed', 'created_at'], name='game_events_user_id_607f49_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['game', 'move_number'], name='game_moves_game_id_2e676a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['player', 'created_at'], name='game_moves_player__f0ac45_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['is_winning_move'], name='game_moves_is_winn_a1159a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gamemove',
            unique_together={('game', 'move_number'), ('game', 'row', 'col')},
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['status', 'created_at'], name='games_status_1725dd_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player', 'status'], name='games_black_p_aed5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white_player', 'status'], name='games_white_p_7b3573_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['finished_at'], name='games_finishe_c13262_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['challenged', 'status'], name='challenges_challen_f06898_idx'),
        ),
    ]
