# Generated by Django 5.2.5 on 2025-08-13 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='gamemove',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['black_player', 'status'], name='games_black_p_aed5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['white_player', 'status'], name='games_white_p_7b3573_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['finished_at'], name='games_finishe_c13262_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['game', 'move_number'], name='game_moves_game_id_2e676a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['player', 'created_at'], name='game_moves_player__f0ac45_idx'),
        ),
        migrations.AddIndex(
            model_name='gamemove',
            index=models.Index(fields=['is_winning_move'], name='game_moves_is_winn_a1159a_idx'),
        ),
    ]
