"""Add all models: RuleSet, User, Game, GameMove

Revision ID: 750418232757
Revises: d4e0143cb440
Create Date: 2025-08-12 17:52:26.056042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750418232757'
down_revision: Union[str, None] = 'd4e0143cb440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
