"""Make white_player_id required in games table

Revision ID: d72264d05025
Revises: 715ec823adf9
Create Date: 2025-08-12 18:50:11.205712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72264d05025'
down_revision: Union[str, None] = '715ec823adf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'white_player_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Foreign key to User (white player)',
               existing_comment='Foreign key to User (white player, nullable for single player)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'white_player_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Foreign key to User (white player, nullable for single player)',
               existing_comment='Foreign key to User (white player)')
    # ### end Alembic commands ###
