# Generated by Django 5.2.5 on 2025-08-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional. Must be unique if provided.', max_length=255, null=True, unique=True),
        ),
    ]
